### ISSUE TITLE
No support for Markdown

### ISSUE THREAD

**Issue by bobrocke** [rockymadden/tomorrow-night-eighties-syntax-theme#7]
Please add syntax coloring for Markdown syntaxes - at least the original, plus GFM. Preferably also Markdown Extra.

**Comment by ryansobol** [comment]
With [this commit](https://github.com/rockymadden/tomorrow-night-eighties-syntax-theme/commit/4b7582db00f992838395b05a4bc5fa0864f5552b), I've improved the base markdown styling for the GFM syntax and have published v0.8.0 of this theme. Feel free to submit pull requests for further improve the styling.
