### ISSUE TITLE
Strange highlighting for braces

### ISSUE THREAD

**Issue by timkelty** [rockymadden/tomorrow-night-eighties-syntax-theme#9]
![screen shot 2015-11-23 at 2 47 26 pm](https://cloud.githubusercontent.com/assets/18329/11347855/44cc4bf2-91f1-11e5-8da6-28e9ba2a85a1.png)

See whitespace highlighting around `if {...}` braces...is this intentional? Seems very odd.

**Comment by ryansobol** [comment]
Is this for the `language-babel` extension?

**Comment by timkelty** [comment]
ah, indeed it is. Normal if I switch the syntax from Babel ES6 Javascript to Javascript...

**Comment by ryansobol** [comment]
I thought so. I've noticed this too and have already looked into it. It seems that the `language-babel` plugin structures the underlying HTML in a way that's impossible to prevent a `background-color` with transparency from being applied into the prepended whitespace. I've wanting to file an issue with them for a while, but have been too busy.

**Comment by timkelty** [comment]
Thanks for the update, I'll stay tuned.

**Comment by ryansobol** [comment]
Not sure which commit to `language-babel` fixed the issue, but it appears to be resolved for me with v2.35.0.
